import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./SharedComps/Navbar";
import Footer from "./SharedComps/Footer";
import clsx from "clsx";
const inter = ({subsets:["inter"], weight:['400','500','600','700'],variable:"--font-inter" })

export const metadata: Metadata = {
  title: "Focusio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx("",inter.variable)} >
      <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
